server:
  port: 8081

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/image_shop?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: passw0rd
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
    config-location: classpath:mybatis-config.xml
    mapper-locations: classpath:mappers/**/*.xml

upload:
  path: C:/upload
